node {
   stage('Preparation') { // for display purposes
      // Get some code from a GitHub repository
      echo 'Hello World'
   }

   stage('Build') {
    echo 'Hello World Build'
    sh '''
        touch  /var/jenkins_home/1655.record;
        touch  /var/jenkins_home/1705.record;
	kubectl get node -owide

    '''
   }

    stage('Copy File From S3') {
    echo 'Hello World Touch'
    sh '''



    '''
   }
   stage('Results') {
      echo 'Hello World'
   }
}


