node {
   stage('Preparation') { // for display purposes
      // Get some code from a GitHub repository
      echo 'Hello World'
   }
  
   stage('Build') {
    echo 'Hello World Build'
    sh '''
        ssh -o StrictHostKeyChecking=no -i /root/uat_hadoop_master.pem  root@172.16.4.151 "touch /tmp/1639.record;touch /tmp/1641.record;
        touch /tmp/1645.record; aws s3 cp s3://opt/zabbix_agt_svr_port_pcap.tgz /tmp/ "
        
    '''
   }
   
    stage('Copy File From S3') {
    echo 'Hello World Touch'
    sh '''
    	   
		   
    
    '''
   }
   stage('Results') {
      echo 'Hello World'
   }
}
